create database USERDB;

use USERDB;

CREATE TABLE IF NOT EXISTS `USER` (
 `USER_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 `USER_NAME` VARCHAR(40) NOT NULL,
 `USER_PASSWORD` VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS `USERPROFILE` (
 `ROLE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 `USER_ID` INT UNSIGNED NOT NULL,
 `USER_ROLE` VARCHAR(40) NOT NULL,
 CONSTRAINT fk1_USER_ID FOREIGN KEY (USER_ID)
 REFERENCES USER(USER_ID)
);